name: 'finflow_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finflow_analytics:
    staging:
      +schema: silver
      +materialized: view
    marts:
      +schema: gold
      +materialized: table